# config/agent_config.yaml
agent_resource_role_arn: "arn:aws:iam::123456789012:role/BedrockAgentRole"
instruction: >
  Eres un agente especializado en el sector financiero. Tu tarea es obtener datos de la cartera del cliente,
  analizar la informaci칩n y evaluar el riesgo de inversi칩n.
foundation_model:
  model_id: "deepseek.r1-v1:0"
  parameters:
    temperature: 0.7
collaboration_mode: "DISABLED"
description: "Agente financiero para an치lisis de carteras e inversi칩n"
tags:
  Proyecto: "FinancieroBedrock"
  Entorno: "Desarrollo"
